SUBROUTINE RQS(M,N,K,M5,N2,A,B,T,TOLER,IFT,X,E,S,WA,WB,NSOL,SOL,DSOL,LSOL,H)
REAL B(M,K),SOL(N2,NSOL),A(M,N),X(N,K),WA(M5,N2),WB(M), E(M),DSOL(M,NSOL)
INTEGER H(1)
DO I=1,K 
CALL RQ(M,N,M5,N2,A,B(1,I),T,TOLER,IFT,X(1,I),E,S,WA,WB,NSOL,NDSOL,SOL,DSOL,LSOL,H)
RETURN
END
