# LaTeX2HTML 96.1 (Feb 5, 1996)
# Associate images original text with physical files.

$key = q/{_inline}$hatsigma^2=z'(I-v(v'v)^-1v')z(n-1)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=261 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline360" SRC="img42.gif"  > '; 
$key = q/{_inline}$pge3${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=44 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline198" SRC="img7.gif"  > '; 
$key = q/{_inline}$z_isimmathcalN(0,1)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=97 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline346" SRC="img37.gif"  > '; 
$key = q/{displaymath}Var(rootofn(tildebeta_n-beta)=sigma^2[1+(5-k(F))qn]+o(n^-1).{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=457 HEIGHT=23 ALIGN=BOTTOM ALT="displaymath316" SRC="img30.gif"  > '; 
$key = q/{_inline}$hatdelta_n${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=16 HEIGHT=39 ALIGN=MIDDLE ALT="tex2html_wrap_inline214" SRC="img10.gif"  > '; 
$key = q/{_inline}$Omega_2n=q${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=62 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline312" SRC="img29.gif"  > '; 
$key = q/{_inline}$r=y-Zhatdelta${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=89 HEIGHT=39 ALIGN=MIDDLE ALT="tex2html_wrap_inline220" SRC="img13.gif"  > '; 
$key = q/{_inline}$Gz_i=1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=61 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline310" SRC="img28.gif"  > '; 
$key = q/{_inline}$G=[I_p,0]'${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=82 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline222" SRC="img14.gif"  > '; 
$key = q/{_inline}$v_isimsqrtchi_nu^2nu${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=98 HEIGHT=37 ALIGN=MIDDLE ALT="tex2html_wrap_inline348" SRC="img38.gif"  > '; 
$key = q/{_inline}$beta${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=10 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline192" SRC="img4.gif"  > '; 
$key = q/{_inline}$V=sigma^2I${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=67 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline286" SRC="img24.gif"  > '; 
$key = q/{_inline}$v_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=12 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline350" SRC="img39.gif"  > '; 
$key = q/{_inline}$hatbeta_n=(X'X)^-1X'y${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=145 HEIGHT=39 ALIGN=MIDDLE ALT="tex2html_wrap_inline194" SRC="img5.gif"  > '; 
$key = q/{_inline}$-(tildebeta_n-beta)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=82 HEIGHT=37 ALIGN=MIDDLE ALT="tex2html_wrap_inline260" SRC="img22.gif"  > '; 
$key = q/{_inline}$nuin{1,3,5}${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=95 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline362" SRC="img43.gif"  > '; 
$key = q/{_inline}${10,15,25,50,75,100}${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=179 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline364" SRC="img44.gif"  > '; 
$key = q/{_inline}$tildebeta_n-beta${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=53 HEIGHT=35 ALIGN=MIDDLE ALT="tex2html_wrap_inline258" SRC="img21.gif"  > '; 
$key = q/{_inline}$hatbeta_n${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=18 HEIGHT=37 ALIGN=MIDDLE ALT="tex2html_wrap_inline196" SRC="img6.gif"  > '; 
$key = q/{_inline}$hatdelta${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=7 HEIGHT=19 ALIGN=BOTTOM ALT="tex2html_wrap_inline328" SRC="img33.gif"  > '; 
$key = q/{_inline}$tildebeta_n=hatbeta_n=bary${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=98 HEIGHT=39 ALIGN=MIDDLE ALT="tex2html_wrap_inline326" SRC="img32.gif"  > '; 
$key = q/{_inline}$delta=Gbeta${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=59 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline224" SRC="img15.gif"  > '; 
$key = q/{_inline}$O(n^-1)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=57 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline288" SRC="img25.gif"  > '; 
$key = q/{_inline}$tildey=(y-hatmu)hatsigma${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=113 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline356" SRC="img40.gif"  > '; 
$key = q/{displaymath}tildebeta_n=e_1'hatV_n^-1hatdeltae_1'hatV_n^-1e_1.{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=340 HEIGHT=24 ALIGN=BOTTOM ALT="displaymath318" SRC="img31.gif"  > '; 
$key = q/{displaymath}hatdelta_n=(Z'Z)^-1Z'y{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=317 HEIGHT=24 ALIGN=BOTTOM ALT="displaymath212" SRC="img9.gif"  > '; 
$key = q/{_inline}$nu=1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=43 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline374" SRC="img45.gif"  > '; 
$key = q/{_inline}$D_n${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=23 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline340" SRC="img35.gif"  > '; 
$key = q/{figure}[!]centerresizeboxtextwidth!includegraphics..fig.1.pscenter{figure}/;
$cached_env_img{$key} = ''; 
$key = q/{_inline}$hatmu=(v'v)^-1v'z${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=116 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline358" SRC="img41.gif"  > '; 
$key = q/{_inline}${u_i}${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=33 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline184" SRC="img2.gif"  > '; 
$key = q/{displaymath}hatV_n=(Z'Z)^-1Z'RZ(Z'Z)^-1{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=360 HEIGHT=24 ALIGN=BOTTOM ALT="displaymath216" SRC="img11.gif"  > '; 
$key = q/{_inline}$Z=[X,D]${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=83 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline210" SRC="img8.gif"  > '; 
$key = q/{_inline}$G=e_1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=54 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline308" SRC="img27.gif"  > '; 
$key = q/{displaymath}y_i=sum_j=1^nx_ijbeta_j+u_iqquadi=1,...,n.{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=387 HEIGHT=921 ALIGN=BOTTOM ALT="displaymath182" SRC="img1.gif"  > '; 
$key = q/{_inline}$tildebeta_n${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=18 HEIGHT=35 ALIGN=MIDDLE ALT="tex2html_wrap_inline190" SRC="img3.gif"  > '; 
$key = q/{displaymath}tildebeta_n=(G'hatV_n^-1G)^-1G'hatV_n^-1hatdelta_n.{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=358 HEIGHT=24 ALIGN=BOTTOM ALT="displaymath230" SRC="img17.gif"  > '; 
$key = q/{_inline}$y_i=z_iv_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=75 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline344" SRC="img36.gif"  > '; 
$key = q/{_inline}$R=diag(r_i^2)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=104 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline218" SRC="img12.gif"  > '; 
$key = q/{displaymath}min(hatdelta-Gbeta)'hatV_n^-1(hatdelta-Gbeta),{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=359 HEIGHT=24 ALIGN=BOTTOM ALT="displaymath228" SRC="img16.gif"  > '; 
$key = q/{_inline}$hatV_n${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=18 HEIGHT=37 ALIGN=MIDDLE ALT="tex2html_wrap_inline244" SRC="img20.gif"  > '; 
$key = q/{_inline}$nrightarrowinfty${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=58 HEIGHT=8 ALIGN=BOTTOM ALT="tex2html_wrap_inline338" SRC="img34.gif"  > '; 
$key = q/{displaymath}tildebeta_n=beta+(G'hatV_n^-1G)^-1G'hatV_n^-1u.{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=372 HEIGHT=24 ALIGN=BOTTOM ALT="displaymath242" SRC="img19.gif"  > '; 
$key = q/{_inline}$Omega_2n${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=28 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline290" SRC="img26.gif"  > '; 

1;

