#figures for unit root rank tests paper
#Test results are generated by the source file HK.s and stored in the
#list HK.test.results, each item in the list is a 3x4x4 array for one of
#the Nelson-Plosser time series.
#
	#1.  l:  lag truncation parameter for Newey West computations
	#2.  tests: Wilcoxon, Normal, Sign in figure they descend in this order 
	#3.  p order of autoregression in ADF model
	#4.  variable number -- names of vars in vnames
#set up the plot
lagl_c(2,4,6,8)
lagp_c(1,2,4,8)
critval_qnorm(c(.01,.05,.1))
lambda_.33 #scaling factor for plot
seg.length_.7
series_c(2,10,(1:14)[-c(2,10)]) #reorder the series
for(k in 1:2){
	s_HK.test.results[[series[k]]]
	out.file_paste("fig.",k,".ps",sep="")
	postscript(out.file,horizontal=F,width=6.5,height=4.5, 
			font=7,pointsize=12)
	plot(c(5,5,1:9),0:10,xlab="lag truncation",
			ylab="order of autoregression",type="n")
	for(i in 1:4){
		y1_kronecker(lagp,c(1,1,1))-.5*seg.length
		x1_kronecker(lagl[i],lambda*(-critval[2]+critval),fun="+")
		y2_kronecker(lagp,c(1,1,1))+.5*seg.length
		x2_kronecker(lagl[i],lambda*(-critval[2]+critval),fun="+")
		segments(x1,y1,x2,y2,col=2)
		for(j in 1:4){
			points(lagl[i]+lambda*(-critval[2]+s[,i,j]),
				lagp[j]+seg.length*c(.4,0,-.4),cex=.5,pch="o")
			}
		}
	}
postscript("fig.3.ps",horizontal=F,font=7,pointsize=10) 
par(mfrow=c(6,2))
for (k in 3:14){
	s_HK.test.results[[series[k]]]
	plot(c(5,5,1:9),0:10,xlab="lag truncation",
			ylab="order of autoregression",type="n")
	for(i in 1:4){
		y1_kronecker(lagp,c(1,1,1))-.5*seg.length
		x1_kronecker(lagl[i],lambda*(-critval[2]+critval),fun="+")
		y2_kronecker(lagp,c(1,1,1))+.5*seg.length
		x2_kronecker(lagl[i],lambda*(-critval[2]+critval),fun="+")
		segments(x1,y1,x2,y2,col=2)
		for(j in 1:4){
			points(lagl[i]+lambda*(-critval[2]+s[,i,j]),
				lagp[j]+seg.length*c(.4,0,-.4),cex=.5,pch="o")
			}
		}
	title(NP.names[series[k]])
	print(paste("s=",k))
	}
